from enum import IntEnum,unique

@unique
class AjaxAction(IntEnum):
    GETTOURNAMENTS=1
    CREATETOURNAMENT=2
    EDITTOURNAMENT=3
    DELETETOURNAMENT=4
    SUBMITPOINTS=5
    RETRIEVEUSERSUBMISSIONS=6
    DECIDEUSERPOINTUSUBMISSION=7
    SUBMITFIGHTS=8
    RETRIEVEFIGHTSSUBMISSIONS=9
    DECIDEFIGHTSSUBMISSION=10
    REVERTSUBMISSION=11
    RETRIEVELEADERBOARD=12
    RETRIEVEUSERSTOFIGHTAGAINST=13

