# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
