# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanuser',
            name='discord_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='discord_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='discord_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
