# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanuser',
            name='discord_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='discord_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='discord_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
