# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsinfo',
            name='masterypointssubtract',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=19),
        ),
    ]
