# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0002_auto_20170102_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanuser',
            name='discord_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='discord_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='discord_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
