# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0002_auto_20161219_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightparticipation',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.ClanUserRoles'),
        ),
    ]
