# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0002_auto_20161220_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordrole',
            name='can_manage_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordrole',
            name='can_manage_wars',
            field=models.BooleanField(default=False),
        ),
    ]
