# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0002_clanuser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordrole',
            name='discord_isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
