# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0003_auto_20170103_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanuser',
            name='discord_discriminator',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
