# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0003_discordrole_discord_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordrole',
            name='discord_permissions',
        ),
    ]
