# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0003_auto_20161220_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanuser',
            name='is_manager',
        ),
    ]
