# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0004_remove_discordrole_discord_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanUserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.DiscordRole')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clanuserroles',
            unique_together=set([('clan_user', 'role')]),
        ),
    ]
