# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0004_discordrole_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsinfo',
            name='masterypointssubtract',
        ),
    ]
