# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0005_auto_20161217_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='discordrole',
            name='id',
        ),
        migrations.AlterField(
            model_name='clanuser',
            name='discord_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clanuserroles',
            name='clan_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discordrole',
            name='discord_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
