# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0005_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsubmission',
            name='managerText',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pointsubmission',
            name='submitterText',
            field=models.TextField(default='', max_length=200),
        ),
    ]
