# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0005_pointsinfo_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpointsubmission',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basicuserpointsubmission',
            name='proof',
            field=models.CharField(max_length=200),
        ),
    ]
