# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0006_auto_20161221_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentFightConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.Fight')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.Tournament')),
            ],
        ),
    ]
