# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0006_auto_20170117_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneononefightsubmission',
            name='proof',
            field=models.CharField(max_length=200),
        ),
    ]
