# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0006_auto_20161217_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsubmission',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='pointsubmission',
            name='proof',
        ),
    ]
