# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 22:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0006_auto_20170206_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('permed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questbuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('dailyquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='sunknightsapp.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestTankMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('dailyquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='sunknightsapp.Quest')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.DiepTank')),
            ],
        ),
        migrations.CreateModel(
            name='QuestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Bonus')], default=1)),
                ('questtext', models.CharField(max_length=500)),
                ('deleted', models.BooleanField(default=False)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sunknightsapp.Quest')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyQuest',
        ),
        migrations.AddField(
            model_name='pointsinfo',
            name='permquestcd',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
