# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0007_auto_20170117_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastery',
            name='date',
        ),
        migrations.AlterField(
            model_name='mastery',
            name='fromSubmission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.BasicUserPointSubmission'),
        ),
    ]
