# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0007_tournamentfightconnector'),
    ]

    operations = [


        migrations.RemoveField(
            model_name='fight',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='winner',
        ),
        migrations.AddField(
            model_name='fight',
            name='team1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='sunknightsapp.DiscordRole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='sunknightsapp.DiscordRole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentfightconnector',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_connector', to='sunknightsapp.Fight'),
        ),
        migrations.AlterField(
            model_name='tournamentfightconnector',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_connectors', to='sunknightsapp.Tournament'),
        ),
    ]
