# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0007_auto_20161217_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('decided', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.PointSubmission')),
            ],
        ),
    ]
