# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0008_auto_20170119_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneononefightsubmission',
            name='expected_outcome',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.5, max_digits=4),
        ),
    ]
