# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0008_auto_20161222_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Finished'), (2, 'Team 1 won'), (3, 'Draw')], default=1),
            preserve_default=False,
        ),
    ]
