# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0009_fight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='finished',
        ),
        migrations.AlterField(
            model_name='fight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Finished'), (2, 'Team 1 "won'), (3, 'Team 2 won'), (4, 'Draw')]),
        ),
    ]
