# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0010_auto_20161222_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPointSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('decided', models.BooleanField(default=False)),
                ('managerText', models.TextField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Fight',
            new_name='GuildFight',
        ),
        migrations.RenameModel(
            old_name='FightParticipation',
            new_name='GuildFightParticipation',
        ),
        migrations.RemoveField(
            model_name='pointsubmission',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='pointsubmission',
            name='pointsinfo',
        ),
        migrations.CreateModel(
            name='BasicUserPointSubmission',
            fields=[
                ('basicpointsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.BasicPointSubmission')),
                ('submitterText', models.TextField(default='', max_length=200)),
                ('proof', models.CharField(max_length=200)),
            ],
            bases=('sunknightsapp.basicpointsubmission',),
        ),
        migrations.CreateModel(
            name='PointsManagerAction',
            fields=[
                ('basicpointsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.BasicPointSubmission')),
            ],
            bases=('sunknightsapp.basicpointsubmission',),
        ),
        migrations.DeleteModel(
            name='PointSubmission',
        ),
        migrations.AddField(
            model_name='basicpointsubmission',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicpointsubmission',
            name='pointsinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='sunknightsapp.PointsInfo'),
        ),
        migrations.CreateModel(
            name='OneOnOneFightSubmission',
            fields=[
                ('basicuserpointsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.BasicUserPointSubmission')),
                ('pointsinfoloser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='sunknightsapp.PointsInfo')),
            ],
            bases=('sunknightsapp.basicuserpointsubmission',),
        ),
    ]
