# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0010_clanuser_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pointsinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='sunknightsapp.PointsInfo')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.DiepTank')),
            ],
            options={
                'ordering': ['tank'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('tank', 'pointsinfo')]),
        ),
    ]
