# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0011_clanuser_country_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='invite_link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
