# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0011_auto_20170122_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunKnightsBadgeRole',
            fields=[
                ('sunknightsguild_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.SunKnightsGuild')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunknightsapp.DiepTank')),
            ],
            bases=('sunknightsapp.sunknightsguild',),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='badge',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='pointsinfo',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='tank',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
