# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0012_basicpointsubmission_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunKnightsGuild',
            fields=[
                ('discordrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.DiscordRole')),
            ],
            bases=('sunknightsapp.discordrole',),
        ),
        migrations.AddField(
            model_name='clanuser',
            name='avatar',
            field=models.CharField(default='https://discordapp.com/assets/6debd47ed13483642cf09e832ed0bc1b.png', max_length=150),
        ),
        migrations.AlterField(
            model_name='basicuserpointsubmission',
            name='proof',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='guildfight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Finished'), (2, 'Team 1 won'), (3, 'Team 2 won'), (4, 'Draw')]),
        ),
        migrations.AlterField(
            model_name='guildfightparticipation',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='sunknightsapp.GuildFight'),
        ),
        migrations.AlterField(
            model_name='guildfightparticipation',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guildfight_guild', to='sunknightsapp.DiscordRole'),
        ),
        migrations.AlterField(
            model_name='guildfightparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guildfight', to=settings.AUTH_USER_MODEL),
        ),
    ]
