# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0012_discordserver_invite_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanUserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_background_enabled', models.BooleanField(default=False)),
                ('custom_background_url', models.CharField(max_length=300)),
                ('clan_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
