# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0012_auto_20170122_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRolePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('discord_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolepoints', to='sunknightsapp.DiscordRole')),
            ],
        ),
    ]
