# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0013_discordrolepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestSubmission',
            fields=[
                ('basicpointsubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sunknightsapp.BasicPointSubmission')),
                ('proof', models.CharField(max_length=200)),
            ],
            bases=('sunknightsapp.basicpointsubmission',),
        ),
    ]
