# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunknightsapp', '0013_auto_20161225_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanuser',
            name='avatar',
            field=models.CharField(default='', max_length=150),
        ),
    ]
